version: '3.7'

services:
  pyspark:
    image: pyspark
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    ports:
      - "8888:8888"
      - "4040:4040"
      - "8080:8080"
      - "18080:18080"
    volumes:
      - /Users/dancastagna/github:/workspace/github
      - /Users/dancastagna/notebooks:/workspace/notebooks
    tty: true
    stdin_open: true
    restart: always
